name: Wrapper - Build & Push

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  build:
    uses: ravencalamitous/devops-central/.github/workflows/build-push.yaml@main
    with:
      service_name: ${{ inputs.service_name }}
      environment: ${{ inputs.environment }}
      branch: ${{ inputs.branch }}
      sha: ${{ inputs.sha }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
